# Generated by Django 3.2.25 on 2025-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.CharField(default='', max_length=200)),
                ('num_department', models.CharField(max_length=3, verbose_name='département')),
                ('postal_code', models.CharField(max_length=5, verbose_name='code postal')),
                ('is_pref', models.BooleanField(default=False, verbose_name='préfecture')),
                ('is_sous_pref', models.BooleanField(default=False, verbose_name='sous-préfecture')),
                ('pref_name', models.CharField(default=models.CharField(max_length=200, verbose_name='nom'), max_length=200)),
                ('code_insee', models.CharField(default='', max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('polygon', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'ville',
                'ordering': ['-is_pref', '-is_sous_pref', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_department', models.CharField(max_length=3)),
                ('polygon', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'département',
                'ordering': ['num_department'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('car_distance', models.IntegerField(default=0.0)),
                ('car_duration', models.IntegerField(default=0.0)),
                ('train_distance', models.IntegerField(default=0.0)),
                ('train_duration', models.IntegerField(default=0.0)),
            ],
            options={
                'verbose_name': 'trajet',
            },
        ),
    ]
